# Generated by Django 3.2.7 on 2021-09-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0003_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
