# Generated by Django 3.2.7 on 2021-09-11 13:03

from django.db import migrations, models
import store_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0004_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[store_api.validators.non_zero_validator]),
        ),
    ]
