# Generated by Django 3.2.7 on 2021-09-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0005_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
